### ISSUE TITLE
Build not working on Ubuntu 12.04

### ISSUE THREAD

**Issue by mpdeimos** [tiliado/diorite#1]
Hi,

I'm trying to build diorite on an Ubuntu 12.04 machine, however, I get the following undefined reference error:

```
/home/mpdeimos/diorite/build/src/glib/ipcmessageserver.c:653: undefined reference to `g_variant_check_format_string'
collect2: ld returned 1 exit status
```

After adding some experimental PPAs/performing an upgrade I get one step further:

```
src/gtk/actionsregistry.c.2.o: In function `diorite_actions_registry_find_and_parse_action':
/home/mpdeimos/diorite/build/src/gtk/actionsregistry.c:902: undefined reference to `g_action_print_detailed_name'
src/gtk/actionsregistry.c.2.o: In function `diorite_actions_registry_build_menu':
/home/mpdeimos/diorite/build/src/gtk/actionsregistry.c:776: undefined reference to `g_menu_item_set_icon'
collect2: ld returned 1 exit status
```

On my arch linux system everything works fine and removing the flags `-Wl,--no-undefined` also works on ubuntu, but this is more or less a hack imho.

This is the output of `waf configure`:

```
$ python2 waf configure
Setting top to                           : /home/mpdeimos/diorite 
Setting out to                           : /home/mpdeimos/diorite/build 
Target platform                          : LINUX 
Install prefix                           : /usr/local/ 
Checking for 'gcc' (c compiler)          : gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'gobject-2.0'               : yes 
Checking for 'gthread-2.0'               : yes 
Checking for program valac-0.8           : not found 
Checking for program valac               : /usr/bin/valac 
Checking for valac version >= (0, 8, 0)  : (0, 24, 0) 
Checking for program valac-0.16          : /usr/bin/valac 
Checking for valac-0.16 version >= (0, 16, 1) : (0, 24, 0) 
Compiler optimizations                        : ON 
Checking for 'glib-2.0' >= 2.32               : yes 
Checking for 'gio-2.0' >= 2.32                : yes 
Checking for 'gtk+-3.0' >= 3.4                : yes 
Checking for 'gdk-3.0' >= 3.4                 : yes 
Checking for 'gthread-2.0' >= 2.32            : yes 
Checking for 'gio-unix-2.0' >= 2.32           : yes 
'configure' finished successfully (0.675s)
```
